name: C/C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shenxianpeng/cpp-linter-action@master
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file

      - name: Check for linting
        if: steps.linter.outputs.checks-failed > 0
        run: |
          echo "Some files failed the linting checks!"

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project source code 
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Compile
        id: compile
        run: |
          g++ --version
          g++ ./assignment-1/*.cpp
        continue-on-error: true

      - name: Check for errors
        if: steps.compile.outcome != 'success'
        run: exit 1
